# Generated by Django 4.2 on 2023-04-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litterarum', '0003_rename_title_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='book author', max_length=200),
        ),
    ]
